---
all:
  children:
    tsi_switches:
      hosts:
        tsi_switch:
          ansible_host: "192.168.99.33"  # local hardware
          # ansible_host: "10.10.20.58"  # devnet reserable
          # ansible_host: "sbx-nxos-mgmt.cisco.com"  # devnet always on
