---
all:
  vars:
    # Content repository parameters
    repo_internal_url: "http://192.168.99.86:8081"
    repo_external_url: "http://192.168.99.86:8081"
    repo_username: "jdoe"
    repo_password: "password321"
    repo_name: "network-data"

    # Override idempotent behavior for testing
    force_change: false
    ansible_python_interpreter: "/usr/bin/env python"

  children:
    tsi_switches:
      hosts:
        tsi_switch:
          ansible_host: "192.168.99.33"  # local hardware
      vars:
        repo_filepath: "files/tsi_switches"
        desired_config: "n3k_baseline9.txt"
        desired_nxos_image: "nxos.7.0.3.I7.8.compact.bin"
        # desired_nxos_image: "nxos.7.0.3.I7.9.compact.bin"

        # Connectivity parameters
        ansible_network_os: "nxos"
        ansible_user: "admin"
        # ansible_password: "Cisco123"  # devnet reservable
        ansible_password: "1qaz@WSX"  # local hardware
        ansible_connection: "network_cli"
        ansible_port: 22
