---
all:
  children:
    tsi_switches:
      hosts:
        tsi_switch:
          ansible_host: "192.168.99.33"  # local hardware
          # ansible_host: "10.10.20.58"  # devnet reserable
          # ansible_host: "sbx-nxos-mgmt.cisco.com"  # devnet always on
      vars:
        desired_config: "n3k_baseline.txt"
        desired_nxos_image: "nxos.7.0.3.I7.8.compact.bin"
        # desired_nxos_image: "nxos.7.0.3.I7.9.compact.bin"

        # Override idempotent behavior for testing
        force_change: false

        # Connectivity parameters
        ansible_python_interpreter: "/usr/bin/env python"
        ansible_network_os: "nxos"
        ansible_user: "admin"
        # ansible_password: "Cisco123"  # devnet reservable
        ansible_password: "1qaz@WSX"  # local hardware
        ansible_connection: "network_cli"
        ansible_port: 22

        # Content repository parameters
        repo_host: "192.168.99.86"
        repo_port: 8081
        repo_user: "jdoe"
        repo_password: "password321"
        repo_name: "network-data"
        repo_filepath: "files/tsi_switches"
        repo_vrf: "management"
