---
- name: "Manage TSI switch baseline config"
  hosts: "tsi_switches"
  tasks:

    - name: "Perform common file download setup tasks"
      include_tasks: "task_file_copy.yml"
      vars:
        desired_file: "{{ desired_config }}"

    - name: "Replace config when hashes do not match or force_change is true"
      block:
        - name: "Replace the existing config with the new one"
          nxos_config:
            # backup: true  # TODO fancy backup to repo?
            replace: "config"
            replace_src: "bootflash:{{ desired_config }}"
            save_when: "modified"

        - name: "Collect config replacement status"
          nxos_command:
            commands: "show config-replace status | json"
          register: "config_status"

        - name: "Ensure config replacement succeeded"
          vars:
            status: "{{ config_status.stdout[0].operation_status }}"
          assert:
            that: "status == 'Success'"
            msg: "Expected config replacement 'Success', saw {{ status }}"
          delegate_to: "localhost"
      when: "not hashes_match or force_change"
...
