---
- name: "Copy desired NX-OS image to device: {{ desired_nxos_file }}"
  cisco.nxos.nxos_file_copy:
    local_file: "{{ filepath }}/{{ desired_nxos_file }}"
    remote_file: "{{ desired_nxos_file }}"
  register: "copy_result"

- name: "Update NX-OS because image file changed"
  block:
    - name: "Copy file and perform installation"
      cisco.nxos.nxos_install_os:
        system_image_file: "{{ desired_nxos_file }}"

    - name: "Wait for device to come online"
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        state: "started"
        timeout: 600
        delay: 2  # use 60 for prod
      delegate_to: "localhost"

    - name: "Collect current NX-OS version"
      nxos_command:
        commands: "show version | json"
      register: "ver_output"

    - name: "Ensure software update succeeded"
      vars:
        cur_ver: "{{ ver_output.stdout[0].nxos_file_name }}"
      assert:
        that: "desired_nxos_file in cur_ver"
        msg: "Expected NX-OS {{ desired_nxos_file }}; saw {{ cur_ver }}"
      delegate_to: "localhost"
  when: "copy_result.changed"
...
